(function () {
  'use strict';
  if (window.__HRA_ENGINE_V2__) return;
  window.__HRA_ENGINE_V2__ = true;

  var I18N = {
    en: {
      annotate:'Annotate', exit:'Exit annotate', hide:'Hide pins', show:'Show pins', comments:'Comments', ready:'Ready', share:'Share HTML',
      title:'Reviewable HTML', close:'Close', copyAI:'Copy for AI', exportMd:'Markdown', exportJson:'JSON', importJson:'Import',
      all:'All', pending:'Open', confirmed:'Accepted', resolved:'Resolved', search:'Search comments…', empty:'No comments match this view.\nTurn on Annotate and click any page element.',
      add:'Add comment', edit:'Edit comment', target:'Target', status:'Status', priority:'Priority', module:'Module / page', author:'Author', note:'Comment',
      notePlaceholder:'Describe the change, why it matters, or the expected result', normal:'Normal', high:'High', low:'Low', remove:'Delete', cancel:'Cancel', save:'Save comment',
      hint:'Annotate mode: click any field, button, card, row, or text. Esc exits.', local:'Saved locally · {page}/{total}; create a share file to send', embedded:'Embedded · {page}/{total}', none:'No comments', shared:'Share file created · {page}/{total}',
      saved:'Saved locally. Create a share file before sending.', deleted:'Comment deleted', required:'Write a comment first', copied:'Copied {n} comments for your AI coding agent', copyFail:'Clipboard unavailable; downloaded Markdown instead',
      sharedToast:'Created a standalone share file with {n} comments', mdToast:'Markdown change list downloaded', jsonToast:'JSON backup downloaded', imported:'Imported {n} comments', importFail:'Could not import this JSON file',
      hiddenTarget:'Open the page, dialog, or drawer that contains this comment first', count:'{n} on this page', file:'File', exportedAt:'Exported', changeList:'HTML review change list',
      aiIntro:'Apply the following review comments to the original HTML. Preserve unrelated layout, behavior, and content. Resolve each item, then summarize the changes made.', selector:'Selector', context:'Context', request:'Requested change'
    },
    zh: {
      annotate:'批注模式', exit:'退出批注', hide:'隐藏标记', show:'显示标记', comments:'批注列表', ready:'准备就绪', share:'生成分享版',
      title:'HTML 产品评审', close:'关闭', copyAI:'复制给 AI', exportMd:'Markdown', exportJson:'JSON', importJson:'导入',
      all:'全部', pending:'待确认', confirmed:'已确认', resolved:'已处理', search:'搜索批注…', empty:'当前筛选下暂无批注。\n开启“批注模式”后点击页面元素即可添加。',
      add:'添加批注', edit:'编辑批注', target:'定位', status:'状态', priority:'优先级', module:'模块 / 页面', author:'批注人', note:'批注内容',
      notePlaceholder:'说明需要修改的内容、原因或预期效果', normal:'普通', high:'高', low:'低', remove:'删除', cancel:'取消', save:'保存批注',
      hint:'批注模式已开启：点击字段、按钮、卡片、表格或文字添加批注，Esc 退出', local:'本机暂存 · 当前页 {page} / 共 {total} 条，需生成分享版', embedded:'文件内置 · 当前页 {page} / 共 {total} 条', none:'暂无批注', shared:'已生成分享版 · 当前页 {page} / 共 {total} 条',
      saved:'批注已保存到本机；生成分享版后才能随文件发送', deleted:'批注已删除', required:'请填写批注内容', copied:'已复制 {n} 条批注，可粘贴给 AI 修改', copyFail:'无法访问剪贴板，已改为下载 Markdown',
      sharedToast:'已生成分享版，共 {n} 条批注，可直接发送', mdToast:'已导出 Markdown 修改清单', jsonToast:'已导出 JSON 备份', imported:'已导入 {n} 条批注', importFail:'无法导入该 JSON 文件',
      hiddenTarget:'该批注所在页面或弹窗当前未打开，请先打开对应位置', count:'当前页 {n} 条', file:'文件', exportedAt:'导出时间', changeList:'HTML 产品评审批注清单',
      aiIntro:'请按照以下批注修改原始 HTML，保留未提及的布局、交互和内容。逐项完成后，汇总说明修改结果。', selector:'选择器', context:'上下文', request:'修改要求'
    }
  };

  var HRA = window.HRA = {
    enabled:false, visible:true, list:[], seedList:[], deletedIds:[], editingId:null, draft:null,
    filter:'all', query:'', inited:false, dirty:false, exportedHash:'', renderQueued:false,
    documentId:'', revisionId:'draft', originalName:'document.html', author:'', locale:'en', storageKey:'', lastFocus:null
  };

  function q(s,r){try{return (r||document).querySelector(s);}catch(e){return null;}}
  function qa(s,r){try{return Array.prototype.slice.call((r||document).querySelectorAll(s));}catch(e){return [];}}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function cssEsc(v){if(window.CSS&&CSS.escape)return CSS.escape(String(v));return String(v).replace(/[^a-zA-Z0-9_-]/g,function(ch){return '\\'+ch;});}
  function attrEsc(v){return String(v).replace(/\\/g,'\\\\').replace(/"/g,'\\"');}
  function safeJson(obj){return JSON.stringify(obj).replace(/</g,'\\u003c');}
  function t(key,vars){var s=(I18N[HRA.locale]||I18N.en)[key]||I18N.en[key]||key;Object.keys(vars||{}).forEach(function(k){s=s.replace(new RegExp('\\{'+k+'\\}','g'),String(vars[k]));});return s;}
  function nowText(){var d=new Date(),p=function(n){return String(n).padStart(2,'0')};return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+' '+p(d.getHours())+':'+p(d.getMinutes());}
  function stamp(){var d=new Date(),p=function(n){return String(n).padStart(2,'0')};return d.getFullYear()+p(d.getMonth()+1)+p(d.getDate())+'_'+p(d.getHours())+p(d.getMinutes());}
  function uid(){return 'hra-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);}
  function parseTime(v){var n=Date.parse(String(v||'').replace(' ','T'));return isNaN(n)?0:n;}
  function visible(el){if(!el||el.nodeType!==1)return false;var s=getComputedStyle(el);if(s.display==='none'||s.visibility==='hidden'||Number(s.opacity)===0)return false;var r=el.getBoundingClientRect();return r.width>0&&r.height>0;}
  function effectiveZ(el){var z=0,cur=el;while(cur&&cur.nodeType===1){var v=parseInt(getComputedStyle(cur).zIndex,10);if(!isNaN(v))z=Math.max(z,v);cur=cur.parentElement;}return z;}
  function domOrder(el){var n=0,cur=el;while(cur&&cur.previousElementSibling){n++;cur=cur.previousElementSibling;}return n;}
  function isModalLike(el){if(!el||el===document.body)return false;var tag=(el.tagName||'').toLowerCase();if(tag==='dialog')return el.hasAttribute('open')||visible(el);if((el.getAttribute('role')||'').toLowerCase()==='dialog'||el.getAttribute('aria-modal')==='true')return true;var c=(' '+(typeof el.className==='string'?el.className:'')+' ').toLowerCase();return /(modal|dialog|drawer|popup|overlay|lightbox|popover)/.test(c);}
  function modalRootFor(el){var arr=[],cur=el;while(cur&&cur!==document.body){if(isModalLike(cur)&&visible(cur))arr.push(cur);cur=cur.parentElement;}if(!arr.length)return null;arr.sort(function(a,b){return effectiveZ(b)-effectiveZ(a)});var best=arr[0];arr.forEach(function(x){if(effectiveZ(x)>=effectiveZ(best)&&x.contains(best))best=x});return best;}
  function modalCandidates(){var sels=['dialog[open]','[role="dialog"]','[aria-modal="true"]','.modal-overlay','.modal','.dialog','.drawer','.popup','.overlay','.ant-modal-wrap','.el-dialog__wrapper','.v-dialog','.MuiDialog-root','.chakra-modal__content-container'];var out=[],seen=[];sels.forEach(function(s){qa(s).forEach(function(el){if(seen.indexOf(el)<0&&visible(el)){seen.push(el);out.push(el);}})});return out;}
  function topModal(){var c=modalCandidates();if(!c.length)return null;c.sort(function(a,b){var z=effectiveZ(b)-effectiveZ(a);if(z)return z;if(a.contains(b))return 1;if(b.contains(a))return -1;return domOrder(b)-domOrder(a);});return modalRootFor(c[0])||c[0];}
  function canonicalPageRootForElement(el){if(!el||el===document.body)return document.body;var p=el.closest&&el.closest('[data-page],.page,[role="tabpanel"]');return p&&!modalRootFor(p)?p:document.body;}
  function primaryPageRoot(){var tiers=['[data-page],.page','[role="tabpanel"]'];for(var i=0;i<tiers.length;i++){var pool=qa(tiers[i]).filter(function(el){return visible(el)&&!modalRootFor(el)&&!el.closest('[data-hra-runtime]')});if(pool.length){var active=pool.filter(function(el){return el.classList.contains('active')||el.getAttribute('aria-hidden')==='false'||el.getAttribute('aria-selected')==='true'});return (active.length?active:pool)[0];}}return document.body;}
  function pageKeyForRoot(root){if(root&&root!==document.body)return 'root:'+getSelector(root,document.body);var bc=q('.breadcrumb-cur,.breadcrumb .active,[aria-current="page"]');if(bc&&bc.textContent.trim())return 'breadcrumb:'+bc.textContent.replace(/\s+/g,' ').trim();var active=q('.sidebar .active,.nav .active,.menu .active');if(active&&active.textContent.trim())return 'nav:'+active.textContent.replace(/\s+/g,' ').trim();return 'location:'+(location.pathname||'')+(location.hash||'');}
  function currentPageKey(){return pageKeyForRoot(primaryPageRoot());}
  function getContext(el){var m=modalRootFor(el);if(m)return {type:'modal',el:m,selector:getSelector(m,document.body),pageKey:currentPageKey()};var p=canonicalPageRootForElement(el);return {type:'page',el:p,selector:getSelector(p,document.body),pageKey:currentPageKey()};}
  function inferredItemPageKey(item){if(item.pageKey)return item.pageKey;if(item.contextSelector){var ctx=q(item.contextSelector);if(ctx&&visible(ctx))return currentPageKey();}return '';}
  function currentPageItems(){var key=currentPageKey();return HRA.list.filter(function(item){var ik=inferredItemPageKey(item);if(ik)return ik===key;var a=resolveAnchor(item);return !!(a&&visible(a)&&itemAllowed(item,a));});}
  function learnVisiblePageKeys(){var key=currentPageKey();HRA.list.forEach(function(item){if(item.pageKey||!item.contextSelector)return;var ctx=q(item.contextSelector);if(ctx&&visible(ctx)&&(item.contextType==='modal'||!topModal()))item.pageKey=key;});}

  function isUnique(sel){try{return document.querySelectorAll(sel).length===1;}catch(e){return false;}}
  function getSelector(el,root){if(!el||el===document.body)return 'body';if(el.id){var id='#'+cssEsc(el.id);if(isUnique(id))return id;}var attrs=['data-testid','data-test','data-qa','data-id','name','aria-label'];for(var i=0;i<attrs.length;i++){var val=el.getAttribute&&el.getAttribute(attrs[i]);if(val){var as='['+attrs[i]+'="'+attrEsc(val)+'"]';if(isUnique(as))return as;}}
    var parts=[],cur=el,limit=0;root=root||document.body;while(cur&&cur.nodeType===1&&cur!==root&&cur!==document.body&&limit++<8){var part=cur.tagName.toLowerCase(),stable=(typeof cur.className==='string'?cur.className.trim().split(/\s+/):[]).filter(function(c){return c&&!/^(active|open|show|selected|current|hover|focus|disabled|is-|has-)/i.test(c)&&!/^hra-/.test(c)}).slice(0,2);if(stable.length)part+='.'+stable.map(cssEsc).join('.');var parent=cur.parentElement;if(parent){var same=Array.prototype.filter.call(parent.children,function(x){return x.tagName===cur.tagName});if(same.length>1)part+=':nth-of-type('+(same.indexOf(cur)+1)+')';}parts.unshift(part);cur=parent;}
    if(root!==document.body&&cur===root)return getSelector(root,document.body)+' > '+parts.join(' > ');return parts.length?parts.join(' > '):'body';
  }
  function findAnchor(target){var el=target&&target.nodeType===1?target:target&&target.parentElement;if(!el)return document.body;return el.closest('button,input,textarea,select,label,a,[role="button"],[role="tab"],tr,td,th,.form-group,.form-field,.field,.control,.card,.item,.row,.cell')||el;}
  function labelFor(el){if(!el)return HRA.locale==='zh'?'当前区域':'Current region';var txt='';if(el.id){var lab=q('label[for="'+cssEsc(el.id)+'"]');if(lab)txt=lab.innerText||lab.textContent||'';}if(!txt)txt=el.getAttribute('aria-label')||el.getAttribute('placeholder')||el.getAttribute('title')||el.getAttribute('name')||'';if(!txt&&/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName||''))txt=el.value||'';if(!txt)txt=(el.innerText||el.textContent||'').trim();txt=txt.replace(/\s+/g,' ').trim();return txt?txt.slice(0,100):(el.tagName||'region').toLowerCase();}
  function guessModule(el){var ctx=getContext(el),heading=q('.modal-title,.dialog-title,[role="heading"],h1,h2,h3',ctx.el);if(heading&&heading.textContent.trim())return heading.textContent.trim().slice(0,60);var active=q('.breadcrumb-cur,.breadcrumb .active,[aria-current="page"],.sidebar .active,.nav .active,.menu .active');if(active)return active.textContent.replace(/\s+/g,' ').trim().slice(0,60);var h=q('h1,h2,h3,.page-title');return h?h.textContent.trim().slice(0,60):(HRA.locale==='zh'?'当前页面':'Current page');}
  function normalizeItem(x){if(!x||typeof x!=='object'||!x.text)return null;var statusMap={'待确认':'pending','已确认':'confirmed','已处理':'resolved',open:'pending',accepted:'confirmed',done:'resolved'};x.status=statusMap[x.status]||x.status||'pending';if(['pending','confirmed','resolved'].indexOf(x.status)<0)x.status='pending';if(['normal','high','low'].indexOf(x.priority)<0)x.priority='normal';x.author=x.author||'';x.module=x.module||(HRA.locale==='zh'?'当前页面':'Current page');return x;}
  function currentHash(){return JSON.stringify(HRA.list.map(function(x){return [x.id,x.updatedAt,x.text,x.status,x.priority,x.module,x.selector]}));}
  function mergeLists(seed,saved,deleted){var map={},del={};(deleted||[]).forEach(function(id){del[id]=1});function put(raw){var x=normalizeItem(raw);if(!x)return;if(!x.id)x.id=uid();if(del[x.id])return;var old=map[x.id];if(!old||parseTime(x.updatedAt||x.createdAt)>=parseTime(old.updatedAt||old.createdAt))map[x.id]=x;}(seed||[]).forEach(put);(saved||[]).forEach(put);var arr=Object.keys(map).map(function(k){return map[k]});arr.sort(function(a,b){return (a.number||999999)-(b.number||999999)||parseTime(a.createdAt)-parseTime(b.createdAt)});var max=0;arr.forEach(function(x){if(!x.number)x.number=++max;else max=Math.max(max,x.number)});return arr;}
  function persist(){HRA.dirty=true;try{localStorage.setItem(HRA.storageKey,JSON.stringify({version:2,items:HRA.list,deletedIds:HRA.deletedIds,savedAt:nowText()}));}catch(e){}updateStatus();}
  function initData(){var meta={};try{meta=JSON.parse((q('#hra-meta')||{}).textContent||'{}')}catch(e){}var lang=meta.locale||'auto';if(lang==='auto')lang=document.documentElement.lang||navigator.language||'en';HRA.locale=/^zh/i.test(lang)?'zh':'en';HRA.documentId=meta.documentId||'html-review-'+location.pathname;HRA.revisionId=meta.revisionId||'draft';HRA.originalName=meta.originalName||decodeURIComponent(location.pathname.split('/').pop()||'document.html');HRA.author=meta.defaultAuthor||'';HRA.storageKey='html_review_annotations_v2_'+HRA.documentId+'_'+HRA.revisionId;var seed=[];try{seed=JSON.parse((q('#hra-annotations-seed')||{}).textContent||'[]')}catch(e){}HRA.seedList=Array.isArray(seed)?seed:[];var saved=[],deleted=[];try{var raw=localStorage.getItem(HRA.storageKey);if(!raw)raw=localStorage.getItem('html_review_annotations_v1_'+HRA.documentId+'_'+HRA.revisionId);if(raw){var obj=JSON.parse(raw);saved=Array.isArray(obj)?obj:(obj.items||[]);deleted=Array.isArray(obj.deletedIds)?obj.deletedIds:[];}}catch(e){}HRA.deletedIds=deleted;HRA.list=mergeLists(HRA.seedList,saved,deleted);HRA.dirty=currentHash()!==JSON.stringify(mergeLists(HRA.seedList,[],[]).map(function(x){return [x.id,x.updatedAt,x.text,x.status,x.priority,x.module,x.selector]}));}

  function legacyMigrate(){if(!window.pmAnnoState||!Array.isArray(window.pmAnnoState.list)||HRA.list.length)return;HRA.list=mergeLists([],window.pmAnnoState.list.map(function(x){return Object.assign({},x,{anchorText:x.anchorText||x.target,contextType:'page',contextSelector:'body'})}),[]);document.body.classList.add('hra-legacy-pm');persist();render();}
  function option(value,label){return '<option value="'+value+'">'+esc(label)+'</option>';}
  function ensureUi(){if(q('#hra-toolbar'))return;var d=document.createElement('div');d.setAttribute('data-hra-runtime','1');d.innerHTML='\
<div id="hra-target-hint" data-hra-runtime>'+esc(t('hint'))+'</div>\
<div id="hra-toolbar" role="toolbar" aria-label="'+esc(t('title'))+'" data-hra-runtime>\
 <button class="hra-btn" id="hra-mode-btn" aria-pressed="false">'+esc(t('annotate'))+'</button>\
 <button class="hra-btn" id="hra-visible-btn" aria-pressed="false">'+esc(t('hide'))+'</button>\
 <button class="hra-btn" id="hra-panel-btn">'+esc(t('comments'))+' <span id="hra-count">0</span></button>\
 <span id="hra-status" aria-live="polite">'+esc(t('ready'))+'</span>\
 <button class="hra-btn primary" id="hra-share-btn">'+esc(t('share'))+'</button>\
</div>\
<aside id="hra-panel" aria-label="'+esc(t('title'))+'" data-hra-runtime>\
 <div class="hra-panel-head"><div class="hra-panel-title">'+esc(t('title'))+'</div><span class="hra-count" id="hra-panel-count">0</span><button class="hra-btn ghost" id="hra-panel-close">'+esc(t('close'))+'</button></div>\
 <div class="hra-panel-actions"><button class="hra-btn primary" id="hra-copy-ai">'+esc(t('copyAI'))+'</button><button class="hra-btn" id="hra-export-list">'+esc(t('exportMd'))+'</button><button class="hra-btn" id="hra-export-json">'+esc(t('exportJson'))+'</button><button class="hra-btn" id="hra-import-btn">'+esc(t('importJson'))+'</button><input id="hra-import-file" type="file" accept="application/json,.json" hidden></div>\
 <div class="hra-summary" id="hra-summary"></div>\
 <div class="hra-filter-row" id="hra-filters"><button class="hra-chip active" data-filter="all">'+esc(t('all'))+'</button><button class="hra-chip" data-filter="pending">'+esc(t('pending'))+'</button><button class="hra-chip" data-filter="confirmed">'+esc(t('confirmed'))+'</button><button class="hra-chip" data-filter="resolved">'+esc(t('resolved'))+'</button></div>\
 <div class="hra-search"><input id="hra-search-input" type="search" placeholder="'+esc(t('search'))+'"></div><div id="hra-list"></div>\
</aside>\
<div id="hra-editor-overlay" role="dialog" aria-modal="true" aria-labelledby="hra-editor-title" data-hra-runtime>\
 <div class="hra-editor"><div class="hra-editor-head"><div class="hra-editor-title" id="hra-editor-title">'+esc(t('add'))+'</div><button class="hra-btn ghost" id="hra-editor-x">'+esc(t('close'))+'</button></div>\
 <div class="hra-editor-body"><div class="hra-anchor">'+esc(t('target'))+': <strong id="hra-anchor-text"></strong></div>\
  <div class="hra-field"><label class="hra-label" for="hra-status-input">'+esc(t('status'))+'</label><select class="hra-select" id="hra-status-input">'+option('pending',t('pending'))+option('confirmed',t('confirmed'))+option('resolved',t('resolved'))+'</select></div>\
  <div class="hra-field"><label class="hra-label" for="hra-priority-input">'+esc(t('priority'))+'</label><select class="hra-select" id="hra-priority-input">'+option('normal',t('normal'))+option('high',t('high'))+option('low',t('low'))+'</select></div>\
  <div class="hra-field"><label class="hra-label" for="hra-module-input">'+esc(t('module'))+'</label><input class="hra-input" id="hra-module-input"></div>\
  <div class="hra-field"><label class="hra-label" for="hra-author-input">'+esc(t('author'))+'</label><input class="hra-input" id="hra-author-input"></div>\
  <div class="hra-field full"><label class="hra-label" for="hra-text-input">'+esc(t('note'))+'</label><textarea class="hra-textarea" id="hra-text-input" placeholder="'+esc(t('notePlaceholder'))+'"></textarea></div>\
 </div><div class="hra-editor-foot"><button class="hra-btn danger" id="hra-delete-btn">'+esc(t('remove'))+'</button><div class="hra-spacer"></div><button class="hra-btn" id="hra-cancel-btn">'+esc(t('cancel'))+'</button><button class="hra-btn primary" id="hra-save-btn">'+esc(t('save'))+'</button></div></div>\
</div><div id="hra-toast" aria-live="polite" data-hra-runtime></div>';
    while(d.firstChild)document.body.appendChild(d.firstChild);d.remove();
    q('#hra-mode-btn').onclick=toggleMode;q('#hra-visible-btn').onclick=toggleVisible;q('#hra-panel-btn').onclick=function(){togglePanel()};q('#hra-panel-close').onclick=function(){togglePanel(false)};q('#hra-share-btn').onclick=exportHtml;q('#hra-copy-ai').onclick=copyForAI;q('#hra-export-list').onclick=exportList;q('#hra-export-json').onclick=exportJson;q('#hra-import-btn').onclick=function(){q('#hra-import-file').click()};q('#hra-import-file').onchange=importJson;q('#hra-search-input').oninput=function(){HRA.query=this.value.trim().toLowerCase();renderList()};q('#hra-editor-x').onclick=closeEditor;q('#hra-cancel-btn').onclick=closeEditor;q('#hra-save-btn').onclick=saveEditor;q('#hra-delete-btn').onclick=deleteCurrent;q('#hra-editor-overlay').addEventListener('mousedown',function(e){if(e.target===this)closeEditor()});qa('#hra-filters .hra-chip').forEach(function(b){b.onclick=function(){HRA.filter=b.getAttribute('data-filter')||'all';qa('#hra-filters .hra-chip').forEach(function(x){x.classList.toggle('active',x===b)});renderList();}});
  }
  function toast(msg){var el=q('#hra-toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(function(){el.classList.remove('show')},2800);}
  function updateStatus(){var el=q('#hra-status');if(!el)return;learnVisiblePageKeys();var page=currentPageItems().length,total=HRA.list.length;if(HRA.exportedHash===currentHash()&&HRA.exportedHash)el.textContent=t('shared',{page:page,total:total});else if(HRA.dirty)el.textContent=t('local',{page:page,total:total});else if(HRA.seedList.length)el.textContent=t('embedded',{page:page,total:total});else el.textContent=t('none');q('#hra-count').textContent=page;q('#hra-panel-count').textContent=t('count',{n:page});}
  function toggleMode(force){HRA.enabled=typeof force==='boolean'?force:!HRA.enabled;document.body.classList.toggle('hra-targeting',HRA.enabled);var b=q('#hra-mode-btn');b.classList.toggle('active',HRA.enabled);b.setAttribute('aria-pressed',String(HRA.enabled));b.textContent=HRA.enabled?t('exit'):t('annotate');}
  function toggleVisible(){HRA.visible=!HRA.visible;document.body.classList.toggle('hra-hidden',!HRA.visible);var b=q('#hra-visible-btn');b.setAttribute('aria-pressed',String(!HRA.visible));b.textContent=HRA.visible?t('hide'):t('show');}
  function togglePanel(force){var p=q('#hra-panel'),on=typeof force==='boolean'?force:!p.classList.contains('open');p.classList.toggle('open',on);if(on){renderList();q('#hra-search-input').focus();}}
  function ignoreClick(el){return !!(el.closest&&el.closest('#hra-toolbar,#hra-panel,#hra-editor-overlay,#hra-toast,.hra-marker,[data-hra-runtime]'));}
  function handleClick(e){if(!HRA.enabled||ignoreClick(e.target))return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();var anchor=findAnchor(e.target),rect=anchor.getBoundingClientRect(),ctx=getContext(anchor);HRA.draft={selector:getSelector(anchor,document.body),relX:rect.width?Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)):.5,relY:rect.height?Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height)):.5,contextType:ctx.type,contextSelector:ctx.selector,pageKey:ctx.pageKey,anchorText:labelFor(anchor),module:guessModule(anchor),fallbackX:e.clientX,fallbackY:e.clientY};openEditor(null);}
  function openEditor(id){HRA.lastFocus=document.activeElement;HRA.editingId=id;var item=id?HRA.list.find(function(x){return x.id===id}):null,d=HRA.draft||{};q('#hra-editor-title').textContent=item?t('edit'):t('add');q('#hra-anchor-text').textContent=item?(item.anchorText||''):(d.anchorText||'');q('#hra-status-input').value=item?item.status:'pending';q('#hra-priority-input').value=item?item.priority:'normal';q('#hra-module-input').value=item?item.module:(d.module||'');q('#hra-author-input').value=item?(item.author||''):HRA.author;q('#hra-text-input').value=item?item.text:'';q('#hra-delete-btn').style.display=item?'':'none';q('#hra-editor-overlay').classList.add('open');setTimeout(function(){q('#hra-text-input').focus()},30);}
  function closeEditor(){q('#hra-editor-overlay').classList.remove('open');HRA.editingId=null;HRA.draft=null;if(HRA.lastFocus&&HRA.lastFocus.focus)HRA.lastFocus.focus();}
  function saveEditor(){var text=q('#hra-text-input').value.trim();if(!text){toast(t('required'));return;}var time=nowText(),item=HRA.list.find(function(x){return x.id===HRA.editingId});if(item){item.status=q('#hra-status-input').value;item.priority=q('#hra-priority-input').value;item.module=q('#hra-module-input').value.trim()||guessModule(document.body);item.author=q('#hra-author-input').value.trim();item.text=text;item.updatedAt=time;}else{var d=HRA.draft||{},number=HRA.list.reduce(function(m,x){return Math.max(m,x.number||0)},0)+1;HRA.list.push({id:uid(),number:number,status:q('#hra-status-input').value,priority:q('#hra-priority-input').value,module:q('#hra-module-input').value.trim()||guessModule(document.body),author:q('#hra-author-input').value.trim(),text:text,anchorText:d.anchorText||'',selector:d.selector||'',relX:typeof d.relX==='number'?d.relX:.5,relY:typeof d.relY==='number'?d.relY:.5,contextType:d.contextType||'page',contextSelector:d.contextSelector||'body',pageKey:d.pageKey||currentPageKey(),fallbackX:d.fallbackX||0,fallbackY:d.fallbackY||0,createdAt:time,updatedAt:time});}persist();closeEditor();render();togglePanel(true);toast(t('saved'));}
  function deleteCurrent(){if(!HRA.editingId)return;var id=HRA.editingId;HRA.list=HRA.list.filter(function(x){return x.id!==id});if(HRA.deletedIds.indexOf(id)<0)HRA.deletedIds.push(id);persist();closeEditor();render();toast(t('deleted'));}
  function resolveAnchor(item){return item.selector?q(item.selector):null;}
  function sameContext(a,b){return !!(a&&b&&(a===b||a.contains(b)||b.contains(a)));}
  function itemAllowed(item,anchor){if(!anchor||!visible(anchor))return false;var pk=inferredItemPageKey(item);if(pk&&pk!==currentPageKey())return false;var tm=topModal(),ctx=item.contextSelector?q(item.contextSelector):null;if(item.contextType==='modal')return !!(ctx&&visible(ctx)&&tm&&sameContext(modalRootFor(ctx)||ctx,tm));return !tm;}
  function markerPos(item,anchor){var r=anchor.getBoundingClientRect();return {left:r.left+r.width*(typeof item.relX==='number'?item.relX:.5),top:r.top+r.height*(typeof item.relY==='number'?item.relY:.5),z:Math.max(900,effectiveZ(modalRootFor(anchor)||anchor)+5)};}
  function render(){learnVisiblePageKeys();qa('.hra-marker').forEach(function(x){x.remove()});if(HRA.visible)HRA.list.forEach(function(item){var a=resolveAnchor(item);if(!itemAllowed(item,a))return;var p=markerPos(item,a),m=document.createElement('button');m.type='button';m.className='hra-marker '+item.priority;m.textContent=item.number||'?';m.title=item.text;m.setAttribute('aria-label',(item.number||'?')+'. '+item.text);m.setAttribute('data-hra-id',item.id);m.style.left=(p.left-13)+'px';m.style.top=(p.top-13)+'px';m.style.zIndex=String(p.z);m.onclick=function(e){e.preventDefault();e.stopPropagation();openEditor(item.id)};document.body.appendChild(m);});renderList();updateStatus();}
  function queueRender(){if(HRA.renderQueued)return;HRA.renderQueued=true;requestAnimationFrame(function(){HRA.renderQueued=false;render()});}
  function statusLabel(v){return t(v==='resolved'?'resolved':v==='confirmed'?'confirmed':'pending');}
  function priorityLabel(v){return t(v==='high'?'high':v==='low'?'low':'normal');}
  function renderSummary(){var items=currentPageItems(),counts={pending:0,confirmed:0,resolved:0};items.forEach(function(x){counts[x.status]=(counts[x.status]||0)+1});q('#hra-summary').innerHTML=[['all',items.length],['pending',counts.pending],['confirmed',counts.confirmed],['resolved',counts.resolved]].map(function(x){return '<div class="hra-summary-item"><div class="hra-summary-num">'+x[1]+'</div><div class="hra-summary-label">'+esc(t(x[0]))+'</div></div>'}).join('');}
  function renderList(){var list=q('#hra-list');if(!list)return;renderSummary();var arr=currentPageItems().filter(function(x){if(HRA.filter!=='all'&&x.status!==HRA.filter)return false;if(!HRA.query)return true;return [x.text,x.module,x.author,x.anchorText,x.selector].join(' ').toLowerCase().indexOf(HRA.query)>=0;});if(!arr.length){list.innerHTML='<div class="hra-empty">'+esc(t('empty')).replace(/\n/g,'<br>')+'</div>';return;}list.innerHTML=arr.map(function(x){return '<button class="hra-card '+esc(x.priority)+'" data-id="'+esc(x.id)+'"><span class="hra-card-top"><span class="hra-no">'+esc(x.number||'?')+'</span><span class="hra-card-module">'+esc(x.module)+'</span><span class="hra-badge">'+esc(statusLabel(x.status))+'</span></span><span class="hra-target">'+esc(t('target'))+': '+esc(x.anchorText||'')+'</span><span class="hra-text">'+esc(x.text)+'</span><span class="hra-meta"><span>'+esc(x.author||'')+'</span><span>'+esc(x.updatedAt||x.createdAt||'')+'</span></span></button>';}).join('');qa('.hra-card',list).forEach(function(c){c.onclick=function(){focusItem(c.getAttribute('data-id'))}});}
  function focusItem(id){var item=HRA.list.find(function(x){return x.id===id}),a=item&&resolveAnchor(item);if(a&&visible(a)&&itemAllowed(item,a)){a.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});setTimeout(function(){openEditor(id)},250);}else toast(t('hiddenTarget'));}
  function markdown(forAI){var lines=[];if(forAI)lines.push(t('aiIntro'),'');else lines.push('# '+t('changeList'),'','- '+t('file')+': '+HRA.originalName,'- '+t('exportedAt')+': '+nowText(),'- '+t('comments')+': '+HRA.list.length,'');HRA.list.forEach(function(x){lines.push('## '+(x.number||'?')+'. '+(x.anchorText||x.module||''),'','- '+t('status')+': '+statusLabel(x.status),'- '+t('priority')+': '+priorityLabel(x.priority),'- '+t('module')+': '+x.module,'- '+t('author')+': '+(x.author||''),'- '+t('selector')+': `'+String(x.selector||'').replace(/`/g,'\\`')+'`','- '+t('context')+': '+(x.contextType||'page')+' / '+(x.pageKey||''),'','**'+t('request')+'**','',x.text,'');});return lines.join('\n');}
  function copyText(value){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(value);return new Promise(function(resolve,reject){var a=document.createElement('textarea');a.value=value;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();try{document.execCommand('copy')?resolve():reject();}catch(e){reject(e);}a.remove();});}
  function copyForAI(){var text=markdown(true);copyText(text).then(function(){toast(t('copied',{n:HRA.list.length}))}).catch(function(){download(baseName()+'_review.md',text,'text/markdown;charset=utf-8');toast(t('copyFail'))});}
  function baseName(){return (HRA.originalName||'document.html').replace(/\.html?$/i,'').replace(/_(批注分享版|review)_\d{8}_\d{4}$/,'');}
  function exportHtml(){var clone=document.documentElement.cloneNode(true);qa('[data-hra-runtime],.hra-marker',clone).forEach(function(x){x.remove()});var body=q('body',clone);if(body)body.classList.remove('hra-targeting','hra-hidden','hra-legacy-pm');var seed=q('#hra-annotations-seed',clone);if(seed)seed.textContent=safeJson(HRA.list);var metaEl=q('#hra-meta',clone),meta={};try{meta=JSON.parse(metaEl.textContent||'{}')}catch(e){}meta.documentId=HRA.documentId;meta.revisionId='share-'+Date.now().toString(36);meta.originalName=HRA.originalName;meta.generatedAt=nowText();meta.annotationCount=HRA.list.length;meta.defaultAuthor=HRA.author;meta.locale=HRA.locale==='zh'?'zh-CN':'en';metaEl.textContent=safeJson(meta);var suffix=HRA.locale==='zh'?'_批注分享版_':'_review_';download(baseName()+suffix+stamp()+'.html','<!DOCTYPE html>\n'+clone.outerHTML,'text/html;charset=utf-8');HRA.exportedHash=currentHash();updateStatus();toast(t('sharedToast',{n:HRA.list.length}));}
  function exportList(){download(baseName()+'_review_'+stamp()+'.md',markdown(false),'text/markdown;charset=utf-8');toast(t('mdToast'));}
  function exportJson(){var data={schemaVersion:1,engine:'html-review-annotation',documentId:HRA.documentId,originalName:HRA.originalName,exportedAt:nowText(),annotations:HRA.list};download(baseName()+'_review_'+stamp()+'.json',JSON.stringify(data,null,2),'application/json;charset=utf-8');toast(t('jsonToast'));}
  function importJson(e){var file=e.target.files&&e.target.files[0];e.target.value='';if(!file)return;var reader=new FileReader();reader.onload=function(){try{var data=JSON.parse(reader.result),items=Array.isArray(data)?data:data.annotations;if(!Array.isArray(items))throw new Error('invalid');var before=HRA.list.length;HRA.list=mergeLists(HRA.list,items,HRA.deletedIds);persist();render();toast(t('imported',{n:Math.max(0,HRA.list.length-before)}));}catch(err){toast(t('importFail'));}};reader.readAsText(file,'utf-8');}
  function download(name,content,type){var blob=new Blob([content],{type:type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1000);}
  function init(){if(HRA.inited)return;HRA.inited=true;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initReady,{once:true});else initReady();}
  function initReady(){initData();ensureUi();if(q('#pm-annotations-seed'))document.body.classList.add('hra-legacy-pm');render();document.addEventListener('click',handleClick,true);window.addEventListener('resize',queueRender,{passive:true});window.addEventListener('scroll',queueRender,true);document.addEventListener('keydown',function(e){var typing=/^(INPUT|TEXTAREA|SELECT)$/.test((e.target&&e.target.tagName)||'')||e.target&&e.target.isContentEditable;if(e.key==='Escape'){if(q('#hra-editor-overlay').classList.contains('open'))closeEditor();else if(HRA.enabled)toggleMode(false);return;}if(typing||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key.toLowerCase()==='a')toggleMode();if(e.key.toLowerCase()==='l')togglePanel();});var mo=new MutationObserver(function(ms){if(ms.some(function(m){return m.type==='attributes'}))queueRender();});mo.observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['class','style','hidden','open','aria-hidden']});setTimeout(legacyMigrate,150);updateStatus();}
  init();
})();
